### ISSUE TITLE
State.Update(Timer.FrameTime) in screens?

### ISSUE THREAD

**Issue by MFernstrom** [GuvaCode/PGF#4]
I'm playing around with the Screens demo, adding an animation to the Main screen.

But following the tutorial here - http://phoenixlib.net/wiki/doku.php?id=tutorial:animation

How do I update State.Update(Timer.FrameTime) in TMainScreen.Update?

**Comment by GuvaCode** [comment]
see demo 13.

procedure TGame.Update;
begin
   Timer.Update;
   Input.Update;

   Screens.Update (Timer.FrameTime);

   Device.Update;

end;

**Comment by GuvaCode** [comment]
> I'm playing around with the Screens demo, adding an animation to the Main screen.
> 
> But following the tutorial here - http://phoenixlib.net/wiki/doku.php?id=tutorial:animation
> 
> How do I update State.Update(Timer.FrameTime) in TMainScreen.Update?

see demo 13.

procedure TGame.Update;
begin
   Timer.Update;
   Input.Update;

   Screens.Update (Timer.FrameTime);

   Device.Update;

end;
