### ISSUE TITLE
Website / Download gone?

### ISSUE THREAD

**Issue by DLPB2** [GuvaCode/PGF#6]
Hi,

https://www.pascalgamedevelopment.com/forum.php  your engine appears to be missing a working download link from here.  Do you no longer have a website or anywhere the project is based?

**Comment by GuvaCode** [comment]
I do not even know who the original author of the engine was. I'm just keeping it in more or less working order. 

If you need the original code, you can search for it here 
https://web.archive.org/web/20240000000000*/%20%20%20%20http://www.phoenixlib.net

**Comment by DLPB2** [comment]
I see.   One last question -- do you knowif this works on Lazarus 32 bit?  I tried to get it working but it threw up a load of errors when trying to install package.  64 bit seems to work.

**Comment by GuvaCode** [comment]
Can I get more details?

**Comment by DLPB2** [comment]
When trying to install on 32 bit Lazarus, the package pgf.lpk complains that libglfw3dll.a isn't found, prob because path for 32 bit isnt  including x86_64-win64.  If you force path, it will then complain numerous dll functions don't exist.  Presumably because the package is compat only with 64 bit lazarus.

**Comment by GuvaCode** [comment]
I have added a library for win32. Please check, I don't have windows

**Comment by DLPB2** [comment]
The package now compiles and installs successfully, but when running one of the demo programs with the 32 bit dll the error is "Execution stopped with exit code -1073741515 C00001352

I have enabled 32 bit program in project options also.

**Comment by DLPB2** [comment]
False alarm -- it's just DLL wasnt present in the folder where the executable was created
