### ISSUE TITLE
Ability to use lazarus / delphi form for rendering

### ISSUE THREAD

**Issue by DLPB2** [GuvaCode/PGF#7]
At the moment, it seems the framework forces the use of a new window.  in Asphyre and a few others you can use the GUI of the form for options, while the client area of the form is used for rendering. Is this possible to implement?

**Comment by GuvaCode** [comment]
> At the moment, it seems the framework forces the use of a new window. in Asphyre and a few others you can use the GUI of the form for options, while the client area of the form is used for rendering. Is this possible to implement?

Yes, it is possible. But so far there is only one for Windows .[https://github.com/GuvaCode/Phoenix-Game-Framework/tree/master/editors/Editor_Delphi/phxModelEditor](url)
